In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [2]:
data='ObesityDataSet_raw_and_data_sinthetic.csv'

In [3]:
df=pd.read_csv(data)

In [4]:
df

Gender        Age    Height      Weight family_history_with_overweight  \
0     Female  21.000000  1.620000   64.000000                            yes   
1     Female  21.000000  1.520000   56.000000                            yes   
2       Male  23.000000  1.800000   77.000000                            yes   
3       Male  27.000000  1.800000   87.000000                             no   
4       Male  22.000000  1.780000   89.800000                             no   
...      ...        ...       ...         ...                            ...   
2106  Female  20.976842  1.710730  131.408528                            yes   
2107  Female  21.982942  1.748584  133.742943                            yes   
2108  Female  22.524036  1.752206  133.689352                            yes   
2109  Female  24.361936  1.739450  133.346641                            yes   
2110  Female  23.664709  1.738836  133.472641                            yes   

     FAVC  FCVC  NCP       CAEC SMOKE      CH2O  SCC       FAF       TUE  \
0      no   2.0  3.0  Sometimes    no  2.000000   no  0.000000  1.000000   
1      no   3.0  3.0  Sometimes   yes  3.000000  yes  3.000000  0.000000   
2      no   2.0  3.0  Sometimes    no  2.000000   no  2.000000  1.000000   
3      no   3.0  3.0  Sometimes    no  2.000000   no  2.000000  0.000000   
4      no   2.0  1.0  Sometimes    no  2.000000   no  0.000000  0.000000   
...   ...   ...  ...        ...   ...       ...  ...       ...       ...   
2106  yes   3.0  3.0  Sometimes    no  1.728139   no  1.676269  0.906247   
2107  yes   3.0  3.0  Sometimes    no  2.005130   no  1.341390  0.599270   
2108  yes   3.0  3.0  Sometimes    no  2.054193   no  1.414209  0.646288   
2109  yes   3.0  3.0  Sometimes    no  2.852339   no  1.139107  0.586035   
2110  yes   3.0  3.0  Sometimes    no  2.863513   no  1.026452  0.714137   

            CALC                 MTRANS           NObeyesdad  
0             no  Public_Transportation        Normal_Weight  
1      Sometimes  Public_Transportation        Normal_Weight  
2     Frequently  Public_Transportation        Normal_Weight  
3     Frequently                Walking   Overweight_Level_I  
4      Sometimes  Public_Transportation  Overweight_Level_II  
...          ...                    ...                  ...  
2106   Sometimes  Public_Transportation     Obesity_Type_III  
2107   Sometimes  Public_Transportation     Obesity_Type_III  
2108   Sometimes  Public_Transportation     Obesity_Type_III  
2109   Sometimes  Public_Transportation     Obesity_Type_III  
2110   Sometimes  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Gender                          2111 non-null   object 
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object 
 5   FAVC                            2111 non-null   object 
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object 
 9   SMOKE                           2111 non-null   object 
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object 
 12  FAF                             21

In [6]:
df.describe()

Age       Height       Weight         FCVC          NCP  \
count  2111.000000  2111.000000  2111.000000  2111.000000  2111.000000   
mean     24.312600     1.701677    86.586058     2.419043     2.685628   
std       6.345968     0.093305    26.191172     0.533927     0.778039   
min      14.000000     1.450000    39.000000     1.000000     1.000000   
25%      19.947192     1.630000    65.473343     2.000000     2.658738   
50%      22.777890     1.700499    83.000000     2.385502     3.000000   
75%      26.000000     1.768464   107.430682     3.000000     3.000000   
max      61.000000     1.980000   173.000000     3.000000     4.000000   

              CH2O          FAF          TUE  
count  2111.000000  2111.000000  2111.000000  
mean      2.008011     1.010298     0.657866  
std       0.612953     0.850592     0.608927  
min       1.000000     0.000000     0.000000  
25%       1.584812     0.124505     0.000000  
50%       2.000000     1.000000     0.625350  
75%       2.477420     1.666678     1.000000  
max       3.000000     3.000000     2.000000

In [7]:
df.shape

(2111, 17)

In [8]:
df.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [4]:
FAF=(df.FAF==0).sum()
TUE=(df.TUE==0).sum()
print("Nilia 0 pada FAF: ",FAF)
print("Nilai 0 pada TUE: ",TUE)

Nilia 0 pada FAF:  411
Nilai 0 pada TUE:  557


In [9]:
df['FAF']=df['FAF'].replace(0,np.NaN)
df['TUE']=df['TUE'].replace(0,np.NaN)

In [594]:
df.shape

(2111, 17)

In [738]:
df

Gender        Age    Height      Weight family_history_with_overweight  \
0     Female  21.000000  1.620000   64.000000                            yes   
1     Female  21.000000  1.520000   56.000000                            yes   
2       Male  23.000000  1.800000   77.000000                            yes   
3       Male  27.000000  1.800000   87.000000                             no   
4       Male  22.000000  1.780000   89.800000                             no   
...      ...        ...       ...         ...                            ...   
2106  Female  20.976842  1.710730  131.408528                            yes   
2107  Female  21.982942  1.748584  133.742943                            yes   
2108  Female  22.524036  1.752206  133.689352                            yes   
2109  Female  24.361936  1.739450  133.346641                            yes   
2110  Female  23.664709  1.738836  133.472641                            yes   

     FAVC  FCVC  NCP       CAEC SMOKE      CH2O  SCC       FAF       TUE  \
0      no   2.0  3.0  Sometimes    no  2.000000   no       NaN  1.000000   
1      no   3.0  3.0  Sometimes   yes  3.000000  yes  3.000000       NaN   
2      no   2.0  3.0  Sometimes    no  2.000000   no  2.000000  1.000000   
3      no   3.0  3.0  Sometimes    no  2.000000   no  2.000000       NaN   
4      no   2.0  1.0  Sometimes    no  2.000000   no       NaN       NaN   
...   ...   ...  ...        ...   ...       ...  ...       ...       ...   
2106  yes   3.0  3.0  Sometimes    no  1.728139   no  1.676269  0.906247   
2107  yes   3.0  3.0  Sometimes    no  2.005130   no  1.341390  0.599270   
2108  yes   3.0  3.0  Sometimes    no  2.054193   no  1.414209  0.646288   
2109  yes   3.0  3.0  Sometimes    no  2.852339   no  1.139107  0.586035   
2110  yes   3.0  3.0  Sometimes    no  2.863513   no  1.026452  0.714137   

            CALC                 MTRANS           NObeyesdad  
0             no  Public_Transportation        Normal_Weight  
1      Sometimes  Public_Transportation        Normal_Weight  
2     Frequently  Public_Transportation        Normal_Weight  
3     Frequently                Walking   Overweight_Level_I  
4      Sometimes  Public_Transportation  Overweight_Level_II  
...          ...                    ...                  ...  
2106   Sometimes  Public_Transportation     Obesity_Type_III  
2107   Sometimes  Public_Transportation     Obesity_Type_III  
2108   Sometimes  Public_Transportation     Obesity_Type_III  
2109   Sometimes  Public_Transportation     Obesity_Type_III  
2110   Sometimes  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

In [10]:
#mengubah data objt menjadi int menggunakan LabelEncoder
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()


In [11]:
#untuk NObeyesdad
NObeyesdad=encoder.fit_transform(df['NObeyesdad'])
NObeyesdad
df['NObeyesdad']=NObeyesdad

In [741]:
df.loc[(df['FAF'].isnull()) & (df['TUE'].isnull())] #ganti nilainya dengan mean

Gender        Age    Height     Weight family_history_with_overweight  \
4       Male  22.000000  1.780000  89.800000                             no   
5       Male  29.000000  1.620000  53.000000                             no   
17    Female  29.000000  1.530000  78.000000                             no   
18    Female  30.000000  1.710000  82.000000                            yes   
19    Female  23.000000  1.650000  70.000000                            yes   
...      ...        ...       ...        ...                            ...   
1440  Female  38.542937  1.517248  79.843221                            yes   
1487  Female  39.126310  1.562889  76.659490                            yes   
1488  Female  37.063599  1.502609  75.279605                            yes   
1489  Female  41.318302  1.544937  77.053948                            yes   
1490  Female  43.726081  1.592316  77.001030                            yes   

     FAVC  FCVC  NCP        CAEC SMOKE      CH2O SCC  FAF  TUE       CALC  \
4      no   2.0  1.0   Sometimes    no  2.000000  no  NaN  NaN  Sometimes   
5     yes   2.0  3.0   Sometimes    no  2.000000  no  NaN  NaN  Sometimes   
17    yes   2.0  1.0   Sometimes    no  2.000000  no  NaN  NaN         no   
18    yes   3.0  4.0  Frequently   yes  1.000000  no  NaN  NaN         no   
19     no   2.0  1.0   Sometimes    no  2.000000  no  NaN  NaN  Sometimes   
...   ...   ...  ...         ...   ...       ...  ..  ...  ...        ...   
1440  yes   2.0  3.0   Sometimes    no  1.095134  no  NaN  NaN  Sometimes   
1487  yes   2.0  3.0   Sometimes    no  1.440526  no  NaN  NaN  Sometimes   
1488  yes   2.0  3.0   Sometimes    no  1.759803  no  NaN  NaN  Sometimes   
1489  yes   2.0  3.0   Sometimes    no  2.090413  no  NaN  NaN  Sometimes   
1490  yes   2.0  3.0   Sometimes    no  2.806922  no  NaN  NaN  Sometimes   

                     MTRANS  NObeyesdad  
4     Public_Transportation           6  
5                Automobile           1  
17               Automobile           2  
18               Automobile           6  
19    Public_Transportation           5  
...                     ...         ...  
1440             Automobile           2  
1487             Automobile           2  
1488             Automobile           2  
1489             Automobile           2  
1490             Automobile           2  

[127 rows x 17 columns]

In [202]:
df.NObeyesdad.value_counts()

2    351
4    324
3    297
5    290
6    290
1    287
0    272
Name: NObeyesdad, dtype: int64

In [12]:
# nilai faf  dengan nilai rata-ratanya
faf_label_0=df[df['NObeyesdad']==0]['FAF'].mean()
print(faf_label_0)
faf_label_1=df[df['NObeyesdad']==1]['FAF'].mean()
print(faf_label_1)
faf_label_2=df[df['NObeyesdad']==2]['FAF'].mean()
print(faf_label_2)
faf_label_3=df[df['NObeyesdad']==3]['FAF'].mean()
print(faf_label_3)
faf_label_4=df[df['NObeyesdad']==4]['FAF'].mean()
print(faf_label_4)
faf_label_5=df[df['NObeyesdad']==5]['FAF'].mean()
print(faf_label_5)
faf_label_6=df[df['NObeyesdad']==6]['FAF'].mean()
print(faf_label_6)



1.4287215252100838
1.7294685990338163
1.2827727481481483
1.0730168773234203
0.9088638523206751
1.2258833639999998
1.213279288209607


In [13]:
# nilai tue  dengan nilai rata-ratanya
tue_label_0=df[df['NObeyesdad']==0]['TUE'].mean()
print(tue_label_0)
tue_label_1=df[df['NObeyesdad']==1]['TUE'].mean()
print(tue_label_1)
tue_label_2=df[df['NObeyesdad']==2]['TUE'].mean()
print(tue_label_2)
tue_label_3=df[df['NObeyesdad']==3]['TUE'].mean()
print(tue_label_3)
tue_label_4=df[df['NObeyesdad']==4]['TUE'].mean()
print(tue_label_4)
tue_label_5=df[df['NObeyesdad']==5]['TUE'].mean()
print(tue_label_5)
tue_label_6=df[df['NObeyesdad']==6]['TUE'].mean()
print(tue_label_6)

1.033180380090498
1.2278481012658229
1.03727819650655
0.7083806898148148
0.6064946253869969
0.930721329842932
0.9361556805555556


In [14]:
#mengganti nilai FAF 
df.loc[df['NObeyesdad']==0,'FAF']=df.loc[df['NObeyesdad']==0,'FAF'].fillna(faf_label_0)
df.loc[df['NObeyesdad']==1,'FAF']=df.loc[df['NObeyesdad']==1,'FAF'].fillna(faf_label_1)
df.loc[df['NObeyesdad']==2,'FAF']=df.loc[df['NObeyesdad']==2,'FAF'].fillna(faf_label_2)
df.loc[df['NObeyesdad']==3,'FAF']=df.loc[df['NObeyesdad']==3,'FAF'].fillna(faf_label_3)
df.loc[df['NObeyesdad']==4,'FAF']=df.loc[df['NObeyesdad']==4,'FAF'].fillna(faf_label_4)
df.loc[df['NObeyesdad']==5,'FAF']=df.loc[df['NObeyesdad']==5,'FAF'].fillna(faf_label_5)
df.loc[df['NObeyesdad']==6,'FAF']=df.loc[df['NObeyesdad']==6,'FAF'].fillna(faf_label_6)


In [15]:
#MENGGANTI NILAI tue
df.loc[df['NObeyesdad']==0,'TUE']=df.loc[df['NObeyesdad']==0,'TUE'].fillna(tue_label_0)
df.loc[df['NObeyesdad']==1,'TUE']=df.loc[df['NObeyesdad']==1,'TUE'].fillna(tue_label_1)
df.loc[df['NObeyesdad']==2,'TUE']=df.loc[df['NObeyesdad']==2,'TUE'].fillna(tue_label_2)
df.loc[df['NObeyesdad']==3,'TUE']=df.loc[df['NObeyesdad']==3,'TUE'].fillna(tue_label_3)
df.loc[df['NObeyesdad']==4,'TUE']=df.loc[df['NObeyesdad']==4,'TUE'].fillna(tue_label_4)
df.loc[df['NObeyesdad']==5,'TUE']=df.loc[df['NObeyesdad']==5,'TUE'].fillna(tue_label_5)
df.loc[df['NObeyesdad']==6,'TUE']=df.loc[df['NObeyesdad']==6,'TUE'].fillna(tue_label_6)


In [16]:
df.shape

(2111, 17)

In [746]:
df.describe()

Age       Height       Weight         FCVC          NCP  \
count  2111.000000  2111.000000  2111.000000  2111.000000  2111.000000   
mean     24.312600     1.701677    86.586058     2.419043     2.685628   
std       6.345968     0.093305    26.191172     0.533927     0.778039   
min      14.000000     1.450000    39.000000     1.000000     1.000000   
25%      19.947192     1.630000    65.473343     2.000000     2.658738   
50%      22.777890     1.700499    83.000000     2.385502     3.000000   
75%      26.000000     1.768464   107.430682     3.000000     3.000000   
max      61.000000     1.980000   173.000000     3.000000     4.000000   

              CH2O          FAF          TUE   NObeyesdad  
count  2111.000000  2111.000000  2111.000000  2111.000000  
mean      2.008011     1.258047     0.921738     3.015632  
std       0.612953     0.700792     0.474112     1.952090  
min       1.000000     0.000096     0.000073     0.000000  
25%       1.584812     0.908864     0.656031     1.000000  
50%       2.000000     1.210736     0.936156     3.000000  
75%       2.477420     1.729469     1.037278     5.000000  
max       3.000000     3.000000     2.000000     6.000000

In [17]:
Q1=df.quantile(0.25)
Q3=df.quantile(0.75)
IQR=Q3-Q1
df=df[~((df<(Q1-1.5*IQR))|(df>(Q3+1.5*IQR))).any(axis=1)]

C:\Users\USER\AppData\Local\Temp\ipykernel_6480\2492161268.py:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q1=df.quantile(0.25)
C:\Users\USER\AppData\Local\Temp\ipykernel_6480\2492161268.py:2: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Q3=df.quantile(0.75)
C:\Users\USER\AppData\Local\Temp\ipykernel_6480\2492161268.py:4: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df=df[~((df<(Q1-1.5*IQR))|(df>(Q3+1.5*IQR))).any(axis=1)]


In [18]:
df

Gender        Age    Height      Weight family_history_with_overweight  \
0     Female  21.000000  1.620000   64.000000                            yes   
2       Male  23.000000  1.800000   77.000000                            yes   
3       Male  27.000000  1.800000   87.000000                             no   
5       Male  29.000000  1.620000   53.000000                             no   
6     Female  23.000000  1.500000   55.000000                            yes   
...      ...        ...       ...         ...                            ...   
2106  Female  20.976842  1.710730  131.408528                            yes   
2107  Female  21.982942  1.748584  133.742943                            yes   
2108  Female  22.524036  1.752206  133.689352                            yes   
2109  Female  24.361936  1.739450  133.346641                            yes   
2110  Female  23.664709  1.738836  133.472641                            yes   

     FAVC  FCVC  NCP       CAEC SMOKE      CH2O SCC       FAF       TUE  \
0      no   2.0  3.0  Sometimes    no  2.000000  no  1.729469  1.000000   
2      no   2.0  3.0  Sometimes    no  2.000000  no  2.000000  1.000000   
3      no   3.0  3.0  Sometimes    no  2.000000  no  2.000000  0.930721   
5     yes   2.0  3.0  Sometimes    no  2.000000  no  1.729469  1.227848   
6     yes   3.0  3.0  Sometimes    no  2.000000  no  1.000000  1.227848   
...   ...   ...  ...        ...   ...       ...  ..       ...       ...   
2106  yes   3.0  3.0  Sometimes    no  1.728139  no  1.676269  0.906247   
2107  yes   3.0  3.0  Sometimes    no  2.005130  no  1.341390  0.599270   
2108  yes   3.0  3.0  Sometimes    no  2.054193  no  1.414209  0.646288   
2109  yes   3.0  3.0  Sometimes    no  2.852339  no  1.139107  0.586035   
2110  yes   3.0  3.0  Sometimes    no  2.863513  no  1.026452  0.714137   

            CALC                 MTRANS  NObeyesdad  
0             no  Public_Transportation           1  
2     Frequently  Public_Transportation           1  
3     Frequently                Walking           5  
5      Sometimes             Automobile           1  
6      Sometimes              Motorbike           1  
...          ...                    ...         ...  
2106   Sometimes  Public_Transportation           4  
2107   Sometimes  Public_Transportation           4  
2108   Sometimes  Public_Transportation           4  
2109   Sometimes  Public_Transportation           4  
2110   Sometimes  Public_Transportation           4  

[1174 rows x 17 columns]

In [19]:
#untuk gender
Gender=encoder.fit_transform(df['Gender'])
Gender

array([0, 1, 1, ..., 0, 0, 0])

In [20]:
#untuk gamily history weight
family_history_with_overweight=encoder.fit_transform(df['family_history_with_overweight'])
family_history_with_overweight

array([1, 1, 0, ..., 1, 1, 1])

In [21]:
#untuk CAEC
CAEC=encoder.fit_transform(df['CAEC'])
CAEC

array([2, 2, 2, ..., 2, 2, 2])

In [22]:
#untuk FAVC
FAVC=encoder.fit_transform(df['FAVC'])
FAVC

array([0, 0, 0, ..., 1, 1, 1])

In [23]:
#untuk SMOKE
SMOKE=encoder.fit_transform(df['SMOKE'])
SMOKE

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
#untuk SCC
SCC=encoder.fit_transform(df['SCC'])
SCC

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
#untuk CALC
CALC=encoder.fit_transform(df['CALC'])
CALC

array([2, 0, 0, ..., 1, 1, 1])

In [26]:
#untuk MTRANS
MTRANS=encoder.fit_transform(df['MTRANS'])
MTRANS

array([3, 3, 4, ..., 3, 3, 3])

In [27]:
df['Gender']=Gender
df['family_history_with_overweight']=family_history_with_overweight
df['CAEC']=CAEC
df['FAVC']=FAVC
df['SCC']=SCC
df['SMOKE']=SMOKE
df['CALC']=CALC
df['MTRANS']=MTRANS



C:\Users\USER\AppData\Local\Temp\ipykernel_6480\488012537.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']=Gender
C:\Users\USER\AppData\Local\Temp\ipykernel_6480\488012537.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['family_history_with_overweight']=family_history_with_overweight
C:\Users\USER\AppData\Local\Temp\ipykernel_6480\488012537.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value 

In [28]:
df

Gender        Age    Height      Weight  family_history_with_overweight  \
0          0  21.000000  1.620000   64.000000                               1   
2          1  23.000000  1.800000   77.000000                               1   
3          1  27.000000  1.800000   87.000000                               0   
5          1  29.000000  1.620000   53.000000                               0   
6          0  23.000000  1.500000   55.000000                               1   
...      ...        ...       ...         ...                             ...   
2106       0  20.976842  1.710730  131.408528                               1   
2107       0  21.982942  1.748584  133.742943                               1   
2108       0  22.524036  1.752206  133.689352                               1   
2109       0  24.361936  1.739450  133.346641                               1   
2110       0  23.664709  1.738836  133.472641                               1   

      FAVC  FCVC  NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  CALC  \
0        0   2.0  3.0     2      0  2.000000    0  1.729469  1.000000     2   
2        0   2.0  3.0     2      0  2.000000    0  2.000000  1.000000     0   
3        0   3.0  3.0     2      0  2.000000    0  2.000000  0.930721     0   
5        1   2.0  3.0     2      0  2.000000    0  1.729469  1.227848     1   
6        1   3.0  3.0     2      0  2.000000    0  1.000000  1.227848     1   
...    ...   ...  ...   ...    ...       ...  ...       ...       ...   ...   
2106     1   3.0  3.0     2      0  1.728139    0  1.676269  0.906247     1   
2107     1   3.0  3.0     2      0  2.005130    0  1.341390  0.599270     1   
2108     1   3.0  3.0     2      0  2.054193    0  1.414209  0.646288     1   
2109     1   3.0  3.0     2      0  2.852339    0  1.139107  0.586035     1   
2110     1   3.0  3.0     2      0  2.863513    0  1.026452  0.714137     1   

      MTRANS  NObeyesdad  
0          3           1  
2          3           1  
3          4           5  
5          0           1  
6          2           1  
...      ...         ...  
2106       3           4  
2107       3           4  
2108       3           4  
2109       3           4  
2110       3           4  

[1174 rows x 17 columns]

In [29]:
import sklearn
from sklearn.model_selection import train_test_split

In [30]:
df.NObeyesdad.value_counts()

4    313
3    178
2    165
1    148
6    142
0    116
5    112
Name: NObeyesdad, dtype: int64

In [31]:
label=df['NObeyesdad']
features=df[['Weight','family_history_with_overweight','Height','Age','FAVC']]

In [32]:
X=features
y=label

In [33]:
#oversampling 
from collections import Counter
from imblearn import under_sampling,over_sampling
from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler()
X_resample,y_resample=ros.fit_resample(X,y)
print(sorted(Counter(y_resample).items()),y_resample.shape)

[(0, 313), (1, 313), (2, 313), (3, 313), (4, 313), (5, 313), (6, 313)] (2191,)


In [34]:
X_resample.shape

(2191, 5)

# Frequent consumption of high caloric food (FAVC), Frequency of consumption of vegetables (FCVC), Number of main meals (NCP), Consumption of food between meals (CAEC), Consumption of water daily (CH20), and Consumption of alcohol (CALC). The attributes related with the physical condition are: Calories consumption monitoring (SCC), Physical activity frequency (FAF), Time using technology devices (TUE), Transportation used (MTRANS),

In [37]:
X_train, X_test, y_train,y_test=train_test_split(X_resample,y_resample,test_size=0.2, random_state=123)

In [36]:
'''uji=pd.DataFrame(X_test)
uji['y_test']=y_test
uji'''

Weight  family_history_with_overweight    Height        Age  FAVC  \
1414   75.000000                               1  1.740000  22.000000     1   
395    87.107317                               0  1.817641  26.787842     1   
2140   84.315608                               1  1.731960  33.015258     1   
927   111.600553                               1  1.643355  26.000000     1   
2105   84.722222                               1  1.713348  34.970367     1   
...          ...                             ...       ...        ...   ...   
1709  112.007101                               1  1.758355  30.003358     1   
956   111.539494                               1  1.640125  26.000000     1   
707   121.253083                               1  1.885543  25.498751     1   
1143  150.377570                               1  1.739457  21.131526     1   
899   111.208963                               1  1.637725  26.000000     1   

      y_test  
1414       1  
395        5  
2140       6  
927        4  
2105       6  
...      ...  
1709       3  
956        4  
707        3  
1143       4  
899        4  

[439 rows x 6 columns]

In [38]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

pred = clf.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[57  0  0  0  0  0  0]
 [ 3 56  0  0  0  2  0]
 [ 0  0 68  0  0  0  0]
 [ 0  0  0 68  0  0  0]
 [ 0  0  0  0 74  0  0]
 [ 0  1  0  0  0 51  2]
 [ 0  0  0  0  0  0 57]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        57
           1       0.98      0.92      0.95        61
           2       1.00      1.00      1.00        68
           3       1.00      1.00      1.00        68
           4       1.00      1.00      1.00        74
           5       0.96      0.94      0.95        54
           6       0.97      1.00      0.98        57

    accuracy                           0.98       439
   macro avg       0.98      0.98      0.98       439
weighted avg       0.98      0.98      0.98       439



In [40]:
def prediction(input_data):
    input_data_as_numpy_array=np.asarray(input_data)
    input_data_reshape=input_data_as_numpy_array.reshape(1,-1)
    input_data_reshape_std=scaler.transform(input_data_reshape)
    prediction=clf.predict(input_data_reshape_std)
    
    print(prediction)

    if (prediction==0):
        print('\nNormal_Weight')
    elif(prediction==1):
        print('\nOverweight_Level_I')
    elif(prediction==2):
        print('\nOverweight_Level_II')
    elif(prediction==3):
        print('\nObesity_Type_I')
    elif (prediction==4):
        print('\nInsufficient_Weight')
    elif(prediction==5):
        print('\nObesity_Type_II')
    else:
        print('\nObesity_Type_III')


In [43]:
weight=input('Masukkan berat badan anda:')
riwayat=input('Ada riwayat obesitas?: ')
riwayat=riwayat.lower()
height=input("Masukkan tinggi badan: ")
Age=input("Masukkan umur: ")
FAVC=input("Sering mengkonsumsi daging?: ")
FAVC=FAVC.lower()

if (riwayat=='iya'):
    riwayat=1
else:
    riwayat=0

if(FAVC=='iya'):
    FAVC=1
else:
    FAVC=0
        


prediction([weight,riwayat,height,Age,FAVC])

[4]

Insufficient_Weight


c:\Users\USER\.conda\envs\main\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [356]:
'''#saving model
import pickle
filename='decision_model.pkl'
pickle.dump(clf,open(filename,'wb'))
pickle.dump(scaler,open('standar.pkl','wb'))'''

In [358]:

'''#loading teh save model
loaded_model=pickle.load(open('decision_model.pkl','rb'))
scaler=pickle.load(open('standar.pkl','rb'))'''